# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('upload_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.IntegerField(max_length=20)),
                ('name', models.TextField(max_length=50)),
                ('mac', models.TextField(max_length=20)),
                ('date', models.DateField(default=datetime.datetime(2017, 4, 1, 15, 38, 17, 394537))),
            ],
        ),
    ]
